# Generated by Django 5.2.14 on 2026-05-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_superenalotto'),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(db_index=True, unique=True)),
                ('wheels', models.JSONField(default=dict)),
                ('raw_text', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-draw_date',),
            },
        ),
        migrations.CreateModel(
            name='TelevideoPageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.SlugField(max_length=32)),
                ('page', models.PositiveSmallIntegerField(db_index=True)),
                ('subpage', models.CharField(blank=True, max_length=8)),
                ('region', models.CharField(blank=True, db_index=True, max_length=32)),
                ('label', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=180)),
                ('content_kind', models.CharField(default='article', max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('source_url', models.URLField(blank=True)),
                ('raw_text', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('section', 'region', 'sort_order', 'page', 'subpage'),
                'constraints': [models.UniqueConstraint(fields=('section', 'page', 'subpage', 'region'), name='unique_televideo_page_snapshot')],
            },
        ),
    ]
