# Generated by Django 5.2.13 on 2026-06-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_lottodraw_televideopagesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenWeatherCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80, unique=True)),
                ('region_slug', models.SlugField(max_length=64)),
                ('query', models.CharField(max_length=120)),
                ('condition', models.CharField(blank=True, max_length=120)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('visibility_m', models.PositiveIntegerField(blank=True, null=True)),
                ('sunrise_at', models.DateTimeField(blank=True, null=True)),
                ('sunset_at', models.DateTimeField(blank=True, null=True)),
                ('timezone_offset', models.IntegerField(default=0)),
                ('today_forecast', models.JSONField(blank=True, default=list)),
                ('forecast_days', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'OpenWeather cities',
                'ordering': ('city',),
            },
        ),
    ]
